services:
    server:
        build: ./backend
        ports:
            - "80:80"
        working_dir: /code/app
        volumes:
            - ./backend:/code/app
        links:
            - db
        environment:
            CHOKIDAR_USEPOLLING: "true"
        restart: on-failure

    webapp:
        build: ./frontend
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
            - HOST_URL=http://192.168.0.10:5000
        ports:
            - "8000:3000"
        volumes:
            - './frontend:/usr/src/app'
            - '/usr/src/app/node_modules'
        links:
            - server

    db:
        image: mongo:latest
        hostname: shop
        ports:
            - 27017:27017
