services:
  server:
    build: .
    command: python -u app.py
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    links:
      - db
  webapp: 
    build: ./frontend
    command: npm start
    ports: 
      - "8000:8000"
    volumes:
      - ./frontend: /webapp
    links:
      - server
  db:
    image: mongo:latest
    hostname: test_shop
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
  